### ISSUE TITLE
我使用的是NestjsConfig3.2.3 当我使用pnpm build后 这个库居然无法拷贝我的Config配置文件 服了！！！

### ISSUE THREAD

**Issue by Wnagfeng** [nestjs/config#1772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

PS C:\Users\Joon\Desktop\LearnNestJs\nest-demo01> pnpm build    

> nest-demo01@0.0.1 build C:\Users\Joon\Desktop\LearnNestJs\nest-demo01
> cross-env NODE_ENV=production nest build

PS C:\Users\Joon\Desktop\LearnNestJs\nest-demo01> cd .\dist\
PS C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist> cd .\src\ 
PS C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src> node .\main.js  
WARNING: No configurations found in configuration directory:C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src\config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\node_modules\.pnpm\config@3.3.12\node_modules\config\lib\config.js:181
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "server" is not defined
    at Config.get (C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\node_modules\.pnpm\config@3.3.12\node_modules\config\lib\config.js:181:11)
    at buildConnectionOptions (C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src\Productconfig\DataBaseConfig.js:9:27)
    at Object.<anonymous> (C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src\Productconfig\DataBaseConfig.js:25:28)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src\app.module.js:14:26)

Node.js v18.12.0

### Minimum reproduction code

https://github.com/Wnagfeng/NestJsTemplate

### Steps to reproduce

PS C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src> node .\main.js  
WARNING: No configurations found in configuration directory:C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src\config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\node_modules\.pnpm\config@3.3.12\node_modules\config\lib\config.js:181
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "server" is not defined
    at Config.get (C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\node_modules\.pnpm\config@3.3.12\node_modules\config\lib\config.js:181:11)
    at buildConnectionOptions (C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src\Productconfig\DataBaseConfig.js:9:27)
    at Object.<anonymous> (C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src\Productconfig\DataBaseConfig.js:25:28)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src\app.module.js:14:26)

Node.js v18.12.0

### Expected behavior

PS C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src> node .\main.js  
WARNING: No configurations found in configuration directory:C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src\config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\node_modules\.pnpm\config@3.3.12\node_modules\config\lib\config.js:181
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "server" is not defined
    at Config.get (C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\node_modules\.pnpm\config@3.3.12\node_modules\config\lib\config.js:181:11)
    at buildConnectionOptions (C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src\Productconfig\DataBaseConfig.js:9:27)
    at Object.<anonymous> (C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src\Productconfig\DataBaseConfig.js:25:28)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\Joon\Desktop\LearnNestJs\nest-demo01\dist\src\app.module.js:14:26)

Node.js v18.12.0

### Package version

^3.2.3

### NestJS version

^10.0.0

### Node.js version

18.12.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

无！！

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
