### ISSUE TITLE
loadEnvFile can attempt to read a directory as a file

### ISSUE THREAD

**Issue by matt1097** [nestjs/config#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using the envFilePath setting of the config module, like:
`ConfigModule.forRoot({
      envFilePath: 'someFile',
    }),
`
If any of the files match a directory name, the loadEnvFile function, only [checks if the path exists](https://github.com/nestjs/config/blob/master/lib/config.module.ts#L181), and not if it is a file before trying to read it.

### Minimum reproduction code

//

### Steps to reproduce

1. Have any nest application
2. Install @nestjs/config
3. Configure the config module with the envFilePath option
e.g.  envFilePath: 'someFile',
5. Create a folder with the same name as a file provided in the above option
With the example of 'someFile' the directory should be named 'someFile' and placed at the same level as the package.json file.
7. Run the application, this can also be replicated with a unit test.
8. See the EISDIR error

### Expected behavior

The matching name directory should be ignored as non-matching

### Package version

2.1.0 & 1.2.1

### NestJS version

8.4.6 & 7.6.18

### Node.js version

14.19.3

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:618:3)
    at tryReadSync (fs.js:383:20)
    at Object.readFileSync (fs.js:420:19)
    at Function.loadEnvFile (D:\checkouts\nestjs-env-test\node_modules\@nestjs\config\dist\config.module.js:162:56)
    at Function.forRoot (D:\checkouts\nestjs-env-test\node_modules\@nestjs\config\dist\config.module.js:62:56)
    at Object.<anonymous> (D:\checkouts\nestjs-env-test\dist\app.module.js:19:35)

**Comment by micalevisk** [comment]
Please provide a [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction). You can start from [this minimal project](https://stackblitz.com/edit/nestjs-issue-minimum-repro-starter?devtoolsheight=33).

[Why Reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

**Comment by matt1097** [comment]
Added a minimum reproduction repo.
Issue did not occur in the stackblitz.com project. But my newly provided repo fails on both my windows box and a Ubuntu 20.04 VM.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
